


Test.elf:Test.o
	gcc Test.o -o Test.elf
Test.o:../Test.c
	gcc ../Test.c -c -o Test.o


all:
	echo all




run:
	echo run
	make debug


debug:
	echo debug


cd:
	echo cd
	pwd
	cd ../..
	pwd

clean:
	rm -rf *.elf *.bin *.o
	cd .. && rm -rf *.elf *.bin *.o





